name: Run RESTassured TestCases

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "25"
          cache: maven
          distribution: "temurin"
      - run: mvn clean test